# timm model
model:
  model_name: mobilenetv2_050
  pretrained: false
  checkpoint_path: null
  drop_rate: null
  num_classes: 5

# optimizer
optimizer:
  opt: Adam
  lr: 1e-3
  weight_decay: 0
  momentum: null
